#i know it only exports only some stuff and not a lot
export arch=mips
export toolarch=mipsel
export linux_version=5.10.271

# Paths relative to the extracted Linux source directory
export kernel_files="
vmlinuz
"
